### ISSUE TITLE
It's too complicated to run the executable

### ISSUE THREAD

**Issue by Eugleo** [Eugleo/java-exam-planner#1]
As OR-Tools are just a C++ library with Java bindings, the users currently have to separately download the C++ code _and_ specify path to the libraries when running the executable ([relevant SO question](https://stackoverflow.com/a/52549840/2421792)).

```shell
java -Djava.library.path="path/to/lib" -jar "path/to/jar"
```

That's sub-optimal, it'd be great if the users just downloaded one executable that would work without any hassle. How could we do that?

**Comment by ahornace** [comment]
The first solution that came to my mind is to distribute the source as a tarball (e.g. https://github.com/oracle/opengrok/releases) and provide a simple `planex.sh/planex` bash script that will contain `java -Djava.library.path="path/to/lib" -jar "path/to/jar"` command.

I will try to investigate more.

**Comment by Eugleo** [comment]
That's a good idea. I tried the following:

```
distributions {
    main {
         from "." {
             include 'src/lib'
         }
    }
}
```

which preserves the directory structure, but `java -Djava.library.path=../src/lib` still doesn't work.

EDIT: Edited the issue to reflect my current problem.

**Comment by Eugleo** [comment]
Never mind, fixed the issue by using APP_HOME_DIR variable and by setting the classPath independently for the distributed packages and the run task.
