### ISSUE TITLE
Add proper build tool

### ISSUE THREAD

**Issue by ahornace** [Eugleo/java-exam-planner#2]
Build tool in a Java project is a must. Pick either Maven or Gradle.

**Comment by Eugleo** [comment]
I installed some 3rd-party libraries using IntelliJ, and somehow I thought it has been configuring some kind of build script behind the scenes (one becomes spoiled by all the automation I guess). Anyway, was that only to install the libraries locally? Just making sure I won't have any clashes once I configure the build script and the dependencies in it.

**Comment by Eugleo** [comment]
Also, with gradle, which files should be on the repo apart from `build.gradle`?

**Comment by ahornace** [comment]
IDEA is doing something behind the scenes but this is generally portable only between IDEA IDEs and is not something commonly used.

I recommend using: https://docs.gradle.org/current/userguide/gradle_wrapper.html

There might be a bunch of files besides `build.gradle`, e.g.:
- gradle.properties
- settings.gradle
- gradlew
- gradle/wrapper/...
...

**Comment by Eugleo** [comment]
I see. By the way, in Gradle docs about adding dependencies make a distinction between _compile-time_ and _runtime_ dependencies. How could a dependency by compile-time or runtime only? For runtime-only I can think of some... precompiled libraries maybe? But for compile-time only I have no clue.

**Comment by ahornace** [comment]
Runtime dependencies are dependencies which are already installed on the target machine and there is no need to bundle them with your project. The simple example of a runtime dependency is servlet specification (e.g. https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api/4.0.0) which is by default provided by many servlet containers (e.g. http://tomcat.apache.org). So it makes no sense to bundle it with the jar (war) since it will be present in the servlet container.

Compile time are ordinary dependencies that need to be bundled with your project because otherwise it would fail while running with the `ClassNotFoundException`.

**Comment by ahornace** [comment]
I think this is the best explanation: https://stackoverflow.com/questions/4270950/compile-time-vs-run-time-dependency-java

Example of a runtime dependency:
`mysql:mysql-connector-java:8.0.18` -> only needs to be accessible when running the code but there is actually no need to be there at compile time because JDBC will load the required classes from this jar using reflection (this is how mainly plugins work)
- you might also check out https://github.com/ahornace/ServiceLoader

Compile time dependency:
if you are using any `class` from the library directly in your code, then it needs to be there at compile time otherwise would compilation fail

I've mixed up provided and compile in my previous answer :D
