### ISSUE TITLE
Add travis/github actions integration

### ISSUE THREAD

**Issue by ahornace** [Eugleo/java-exam-planner#4]
It would be cool to have a simple CI.

**Comment by Eugleo** [comment]
I added the default Gradle GitHub action, but I can't seem to set it up correctly for Windows. Do you have any idea where the problem might be? I don't have any experience with Windows machines.

**Comment by ahornace** [comment]
> I added the default Gradle GitHub action, but I can't seem to set it up correctly for Windows. Do you have any idea where the problem might be? I don't have any experience with Windows machines.

Me neither. Last time I was on Windows was 5-6 years earlier :/ Maybe `gradlew.bat` does not have execute permission (I'm not even sure Windows have a notion of such thing). Have you tried `.\gradlew.bat`?

It depends on the target audience of your program. If you would like to promote the program to users outside of informatics section at MFF, then try to solve it. If not, then don't bother with it.

**Comment by Eugleo** [comment]
That was a good guess! Now the CI passes for both systems. I'd actually like my classmates to be able to use it, and most of them are on Windows. (Not sure if they'll want to build from source, but whatever)
